[redis]
host=redis

[s3]
access_key = mwdb
secret_key = mwdbmwdb
address = http://minio:9000
bucket = karton

[mwdb]
api_url = http://mwdb.:8080/api/
username = admin
password = admin

[cape]
api_url = http://10.20.20.111:8000
api_token = 706edf9c35e808de362bf434c377d3c2f6840615
poll_interval = 30
max_wait_time = 1800
timeout = 300
package = exe
screenshots = true
procmon = true

; [VT]
; api_url = https://www.virustotal.com/api/v3
; api_key = YOUR_API_KEY
